// Code generated by ent, DO NOT EDIT.

package summary

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the summary type in the database.
	Label = "summary"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldSenderID holds the string denoting the sender_id field in the database.
	FieldSenderID = "sender_id"
	// FieldSenderName holds the string denoting the sender_name field in the database.
	FieldSenderName = "sender_name"
	// FieldSenderUsername holds the string denoting the sender_username field in the database.
	FieldSenderUsername = "sender_username"
	// FieldSenderNickname holds the string denoting the sender_nickname field in the database.
	FieldSenderNickname = "sender_nickname"
	// FieldSummaryDate holds the string denoting the summary_date field in the database.
	FieldSummaryDate = "summary_date"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// Table holds the table name of the summary in the database.
	Table = "summaries"
)

// Columns holds all SQL columns for summary fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldChatID,
	FieldSenderID,
	FieldSenderName,
	FieldSenderUsername,
	FieldSenderNickname,
	FieldSummaryDate,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// OrderOption defines the ordering options for the Summary queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// BySenderID orders the results by the sender_id field.
func BySenderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderID, opts...).ToFunc()
}

// BySenderName orders the results by the sender_name field.
func BySenderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderName, opts...).ToFunc()
}

// BySenderUsername orders the results by the sender_username field.
func BySenderUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderUsername, opts...).ToFunc()
}

// BySenderNickname orders the results by the sender_nickname field.
func BySenderNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderNickname, opts...).ToFunc()
}

// BySummaryDate orders the results by the summary_date field.
func BySummaryDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummaryDate, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}
