// Code generated by ent, DO NOT EDIT.

package summary

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/talk-trace-bot/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldUpdateTime, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldChatID, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderID, v))
}

// SenderName applies equality check predicate on the "sender_name" field. It's identical to SenderNameEQ.
func SenderName(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderName, v))
}

// SenderUsername applies equality check predicate on the "sender_username" field. It's identical to SenderUsernameEQ.
func SenderUsername(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderUsername, v))
}

// SenderNickname applies equality check predicate on the "sender_nickname" field. It's identical to SenderNicknameEQ.
func SenderNickname(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderNickname, v))
}

// SummaryDate applies equality check predicate on the "summary_date" field. It's identical to SummaryDateEQ.
func SummaryDate(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSummaryDate, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldContent, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldUpdateTime, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int64) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int64) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldChatID, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v int64) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldSenderID, v))
}

// SenderNameEQ applies the EQ predicate on the "sender_name" field.
func SenderNameEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderName, v))
}

// SenderNameNEQ applies the NEQ predicate on the "sender_name" field.
func SenderNameNEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldSenderName, v))
}

// SenderNameIn applies the In predicate on the "sender_name" field.
func SenderNameIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldSenderName, vs...))
}

// SenderNameNotIn applies the NotIn predicate on the "sender_name" field.
func SenderNameNotIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldSenderName, vs...))
}

// SenderNameGT applies the GT predicate on the "sender_name" field.
func SenderNameGT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldSenderName, v))
}

// SenderNameGTE applies the GTE predicate on the "sender_name" field.
func SenderNameGTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldSenderName, v))
}

// SenderNameLT applies the LT predicate on the "sender_name" field.
func SenderNameLT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldSenderName, v))
}

// SenderNameLTE applies the LTE predicate on the "sender_name" field.
func SenderNameLTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldSenderName, v))
}

// SenderNameContains applies the Contains predicate on the "sender_name" field.
func SenderNameContains(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContains(FieldSenderName, v))
}

// SenderNameHasPrefix applies the HasPrefix predicate on the "sender_name" field.
func SenderNameHasPrefix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasPrefix(FieldSenderName, v))
}

// SenderNameHasSuffix applies the HasSuffix predicate on the "sender_name" field.
func SenderNameHasSuffix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasSuffix(FieldSenderName, v))
}

// SenderNameEqualFold applies the EqualFold predicate on the "sender_name" field.
func SenderNameEqualFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEqualFold(FieldSenderName, v))
}

// SenderNameContainsFold applies the ContainsFold predicate on the "sender_name" field.
func SenderNameContainsFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContainsFold(FieldSenderName, v))
}

// SenderUsernameEQ applies the EQ predicate on the "sender_username" field.
func SenderUsernameEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderUsername, v))
}

// SenderUsernameNEQ applies the NEQ predicate on the "sender_username" field.
func SenderUsernameNEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldSenderUsername, v))
}

// SenderUsernameIn applies the In predicate on the "sender_username" field.
func SenderUsernameIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldSenderUsername, vs...))
}

// SenderUsernameNotIn applies the NotIn predicate on the "sender_username" field.
func SenderUsernameNotIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldSenderUsername, vs...))
}

// SenderUsernameGT applies the GT predicate on the "sender_username" field.
func SenderUsernameGT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldSenderUsername, v))
}

// SenderUsernameGTE applies the GTE predicate on the "sender_username" field.
func SenderUsernameGTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldSenderUsername, v))
}

// SenderUsernameLT applies the LT predicate on the "sender_username" field.
func SenderUsernameLT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldSenderUsername, v))
}

// SenderUsernameLTE applies the LTE predicate on the "sender_username" field.
func SenderUsernameLTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldSenderUsername, v))
}

// SenderUsernameContains applies the Contains predicate on the "sender_username" field.
func SenderUsernameContains(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContains(FieldSenderUsername, v))
}

// SenderUsernameHasPrefix applies the HasPrefix predicate on the "sender_username" field.
func SenderUsernameHasPrefix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasPrefix(FieldSenderUsername, v))
}

// SenderUsernameHasSuffix applies the HasSuffix predicate on the "sender_username" field.
func SenderUsernameHasSuffix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasSuffix(FieldSenderUsername, v))
}

// SenderUsernameIsNil applies the IsNil predicate on the "sender_username" field.
func SenderUsernameIsNil() predicate.Summary {
	return predicate.Summary(sql.FieldIsNull(FieldSenderUsername))
}

// SenderUsernameNotNil applies the NotNil predicate on the "sender_username" field.
func SenderUsernameNotNil() predicate.Summary {
	return predicate.Summary(sql.FieldNotNull(FieldSenderUsername))
}

// SenderUsernameEqualFold applies the EqualFold predicate on the "sender_username" field.
func SenderUsernameEqualFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEqualFold(FieldSenderUsername, v))
}

// SenderUsernameContainsFold applies the ContainsFold predicate on the "sender_username" field.
func SenderUsernameContainsFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContainsFold(FieldSenderUsername, v))
}

// SenderNicknameEQ applies the EQ predicate on the "sender_nickname" field.
func SenderNicknameEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSenderNickname, v))
}

// SenderNicknameNEQ applies the NEQ predicate on the "sender_nickname" field.
func SenderNicknameNEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldSenderNickname, v))
}

// SenderNicknameIn applies the In predicate on the "sender_nickname" field.
func SenderNicknameIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldSenderNickname, vs...))
}

// SenderNicknameNotIn applies the NotIn predicate on the "sender_nickname" field.
func SenderNicknameNotIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldSenderNickname, vs...))
}

// SenderNicknameGT applies the GT predicate on the "sender_nickname" field.
func SenderNicknameGT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldSenderNickname, v))
}

// SenderNicknameGTE applies the GTE predicate on the "sender_nickname" field.
func SenderNicknameGTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldSenderNickname, v))
}

// SenderNicknameLT applies the LT predicate on the "sender_nickname" field.
func SenderNicknameLT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldSenderNickname, v))
}

// SenderNicknameLTE applies the LTE predicate on the "sender_nickname" field.
func SenderNicknameLTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldSenderNickname, v))
}

// SenderNicknameContains applies the Contains predicate on the "sender_nickname" field.
func SenderNicknameContains(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContains(FieldSenderNickname, v))
}

// SenderNicknameHasPrefix applies the HasPrefix predicate on the "sender_nickname" field.
func SenderNicknameHasPrefix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasPrefix(FieldSenderNickname, v))
}

// SenderNicknameHasSuffix applies the HasSuffix predicate on the "sender_nickname" field.
func SenderNicknameHasSuffix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasSuffix(FieldSenderNickname, v))
}

// SenderNicknameIsNil applies the IsNil predicate on the "sender_nickname" field.
func SenderNicknameIsNil() predicate.Summary {
	return predicate.Summary(sql.FieldIsNull(FieldSenderNickname))
}

// SenderNicknameNotNil applies the NotNil predicate on the "sender_nickname" field.
func SenderNicknameNotNil() predicate.Summary {
	return predicate.Summary(sql.FieldNotNull(FieldSenderNickname))
}

// SenderNicknameEqualFold applies the EqualFold predicate on the "sender_nickname" field.
func SenderNicknameEqualFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEqualFold(FieldSenderNickname, v))
}

// SenderNicknameContainsFold applies the ContainsFold predicate on the "sender_nickname" field.
func SenderNicknameContainsFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContainsFold(FieldSenderNickname, v))
}

// SummaryDateEQ applies the EQ predicate on the "summary_date" field.
func SummaryDateEQ(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldSummaryDate, v))
}

// SummaryDateNEQ applies the NEQ predicate on the "summary_date" field.
func SummaryDateNEQ(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldSummaryDate, v))
}

// SummaryDateIn applies the In predicate on the "summary_date" field.
func SummaryDateIn(vs ...time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldSummaryDate, vs...))
}

// SummaryDateNotIn applies the NotIn predicate on the "summary_date" field.
func SummaryDateNotIn(vs ...time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldSummaryDate, vs...))
}

// SummaryDateGT applies the GT predicate on the "summary_date" field.
func SummaryDateGT(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldSummaryDate, v))
}

// SummaryDateGTE applies the GTE predicate on the "summary_date" field.
func SummaryDateGTE(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldSummaryDate, v))
}

// SummaryDateLT applies the LT predicate on the "summary_date" field.
func SummaryDateLT(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldSummaryDate, v))
}

// SummaryDateLTE applies the LTE predicate on the "summary_date" field.
func SummaryDateLTE(v time.Time) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldSummaryDate, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Summary {
	return predicate.Summary(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Summary {
	return predicate.Summary(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Summary {
	return predicate.Summary(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Summary {
	return predicate.Summary(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Summary {
	return predicate.Summary(sql.FieldContainsFold(FieldContent, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Summary) predicate.Summary {
	return predicate.Summary(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Summary) predicate.Summary {
	return predicate.Summary(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Summary) predicate.Summary {
	return predicate.Summary(sql.NotPredicates(p))
}
