// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DailyRunsColumns holds the columns for the "daily_runs" table.
	DailyRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "in_progress", "completed", "failed"}, Default: "in_progress"},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
	}
	// DailyRunsTable holds the schema information for the "daily_runs" table.
	DailyRunsTable = &schema.Table{
		Name:       "daily_runs",
		Columns:    DailyRunsColumns,
		PrimaryKey: []*schema.Column{DailyRunsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dailyrun_start_time_end_time",
				Unique:  true,
				Columns: []*schema.Column{DailyRunsColumns[3], DailyRunsColumns[4]},
			},
			{
				Name:    "dailyrun_status",
				Unique:  false,
				Columns: []*schema.Column{DailyRunsColumns[5]},
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "message_id", Type: field.TypeInt64},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "sender_id", Type: field.TypeInt64},
		{Name: "sender_name", Type: field.TypeString},
		{Name: "sender_username", Type: field.TypeString, Nullable: true},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "sent_at", Type: field.TypeTime},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
	}
	// SummariesColumns holds the columns for the "summaries" table.
	SummariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "sender_id", Type: field.TypeInt64},
		{Name: "sender_name", Type: field.TypeString},
		{Name: "sender_username", Type: field.TypeString, Nullable: true},
		{Name: "sender_nickname", Type: field.TypeString, Nullable: true},
		{Name: "summary_date", Type: field.TypeTime},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
	}
	// SummariesTable holds the schema information for the "summaries" table.
	SummariesTable = &schema.Table{
		Name:       "summaries",
		Columns:    SummariesColumns,
		PrimaryKey: []*schema.Column{SummariesColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed"}, Default: "pending"},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "summary_content", Type: field.TypeString, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "task_chat_id_start_time_end_time",
				Unique:  true,
				Columns: []*schema.Column{TasksColumns[3], TasksColumns[4], TasksColumns[5]},
			},
			{
				Name:    "task_status",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DailyRunsTable,
		MessagesTable,
		SummariesTable,
		TasksTable,
	}
)

func init() {
}
