// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/talk-trace-bot/internal/ent/dailyrun"
)

// DailyRunCreate is the builder for creating a DailyRun entity.
type DailyRunCreate struct {
	config
	mutation *DailyRunMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *DailyRunCreate) SetCreateTime(v time.Time) *DailyRunCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *DailyRunCreate) SetNillableCreateTime(v *time.Time) *DailyRunCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *DailyRunCreate) SetUpdateTime(v time.Time) *DailyRunCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *DailyRunCreate) SetNillableUpdateTime(v *time.Time) *DailyRunCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *DailyRunCreate) SetStartTime(v time.Time) *DailyRunCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *DailyRunCreate) SetEndTime(v time.Time) *DailyRunCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DailyRunCreate) SetStatus(v dailyrun.Status) *DailyRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DailyRunCreate) SetNillableStatus(v *dailyrun.Status) *DailyRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *DailyRunCreate) SetErrorMessage(v string) *DailyRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *DailyRunCreate) SetNillableErrorMessage(v *string) *DailyRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// Mutation returns the DailyRunMutation object of the builder.
func (_c *DailyRunCreate) Mutation() *DailyRunMutation {
	return _c.mutation
}

// Save creates the DailyRun in the database.
func (_c *DailyRunCreate) Save(ctx context.Context) (*DailyRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyRunCreate) SaveX(ctx context.Context) *DailyRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DailyRunCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := dailyrun.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := dailyrun.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := dailyrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyRunCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "DailyRun.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "DailyRun.update_time"`)}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "DailyRun.start_time"`)}
	}
	if _, ok := _c.mutation.EndTime(); !ok {
		return &ValidationError{Name: "end_time", err: errors.New(`ent: missing required field "DailyRun.end_time"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DailyRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := dailyrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DailyRun.status": %w`, err)}
		}
	}
	return nil
}

func (_c *DailyRunCreate) sqlSave(ctx context.Context) (*DailyRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyRunCreate) createSpec() (*DailyRun, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailyrun.Table, sqlgraph.NewFieldSpec(dailyrun.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(dailyrun.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(dailyrun.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(dailyrun.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(dailyrun.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(dailyrun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(dailyrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	return _node, _spec
}

// DailyRunCreateBulk is the builder for creating many DailyRun entities in bulk.
type DailyRunCreateBulk struct {
	config
	err      error
	builders []*DailyRunCreate
}

// Save creates the DailyRun entities in the database.
func (_c *DailyRunCreateBulk) Save(ctx context.Context) ([]*DailyRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyRunCreateBulk) SaveX(ctx context.Context) []*DailyRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
