// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/talk-trace-bot/internal/ent/dailyrun"
	"github.com/fachebot/talk-trace-bot/internal/ent/predicate"
)

// DailyRunUpdate is the builder for updating DailyRun entities.
type DailyRunUpdate struct {
	config
	hooks    []Hook
	mutation *DailyRunMutation
}

// Where appends a list predicates to the DailyRunUpdate builder.
func (_u *DailyRunUpdate) Where(ps ...predicate.DailyRun) *DailyRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DailyRunUpdate) SetUpdateTime(v time.Time) *DailyRunUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *DailyRunUpdate) SetStartTime(v time.Time) *DailyRunUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *DailyRunUpdate) SetNillableStartTime(v *time.Time) *DailyRunUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *DailyRunUpdate) SetEndTime(v time.Time) *DailyRunUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *DailyRunUpdate) SetNillableEndTime(v *time.Time) *DailyRunUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DailyRunUpdate) SetStatus(v dailyrun.Status) *DailyRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DailyRunUpdate) SetNillableStatus(v *dailyrun.Status) *DailyRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DailyRunUpdate) SetErrorMessage(v string) *DailyRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DailyRunUpdate) SetNillableErrorMessage(v *string) *DailyRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DailyRunUpdate) ClearErrorMessage() *DailyRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the DailyRunMutation object of the builder.
func (_u *DailyRunUpdate) Mutation() *DailyRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := dailyrun.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dailyrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DailyRun.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailyrun.Table, dailyrun.Columns, sqlgraph.NewFieldSpec(dailyrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(dailyrun.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(dailyrun.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(dailyrun.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dailyrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(dailyrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(dailyrun.FieldErrorMessage, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailyrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyRunUpdateOne is the builder for updating a single DailyRun entity.
type DailyRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyRunMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *DailyRunUpdateOne) SetUpdateTime(v time.Time) *DailyRunUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *DailyRunUpdateOne) SetStartTime(v time.Time) *DailyRunUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *DailyRunUpdateOne) SetNillableStartTime(v *time.Time) *DailyRunUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *DailyRunUpdateOne) SetEndTime(v time.Time) *DailyRunUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *DailyRunUpdateOne) SetNillableEndTime(v *time.Time) *DailyRunUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DailyRunUpdateOne) SetStatus(v dailyrun.Status) *DailyRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DailyRunUpdateOne) SetNillableStatus(v *dailyrun.Status) *DailyRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DailyRunUpdateOne) SetErrorMessage(v string) *DailyRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DailyRunUpdateOne) SetNillableErrorMessage(v *string) *DailyRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DailyRunUpdateOne) ClearErrorMessage() *DailyRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the DailyRunMutation object of the builder.
func (_u *DailyRunUpdateOne) Mutation() *DailyRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the DailyRunUpdate builder.
func (_u *DailyRunUpdateOne) Where(ps ...predicate.DailyRun) *DailyRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyRunUpdateOne) Select(field string, fields ...string) *DailyRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyRun entity.
func (_u *DailyRunUpdateOne) Save(ctx context.Context) (*DailyRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyRunUpdateOne) SaveX(ctx context.Context) *DailyRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := dailyrun.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dailyrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DailyRun.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyRunUpdateOne) sqlSave(ctx context.Context) (_node *DailyRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailyrun.Table, dailyrun.Columns, sqlgraph.NewFieldSpec(dailyrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailyrun.FieldID)
		for _, f := range fields {
			if !dailyrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailyrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(dailyrun.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(dailyrun.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(dailyrun.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dailyrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(dailyrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(dailyrun.FieldErrorMessage, field.TypeString)
	}
	_node = &DailyRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailyrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
