// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/talk-trace-bot/internal/ent/message"
	"github.com/fachebot/talk-trace-bot/internal/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *MessageUpdate) SetUpdateTime(v time.Time) *MessageUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MessageUpdate) SetMessageID(v int64) *MessageUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableMessageID(v *int64) *MessageUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *MessageUpdate) AddMessageID(v int64) *MessageUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *MessageUpdate) SetChatID(v int64) *MessageUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableChatID(v *int64) *MessageUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *MessageUpdate) AddChatID(v int64) *MessageUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *MessageUpdate) SetSenderID(v int64) *MessageUpdate {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSenderID(v *int64) *MessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *MessageUpdate) AddSenderID(v int64) *MessageUpdate {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *MessageUpdate) SetSenderName(v string) *MessageUpdate {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSenderName(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetSenderUsername sets the "sender_username" field.
func (_u *MessageUpdate) SetSenderUsername(v string) *MessageUpdate {
	_u.mutation.SetSenderUsername(v)
	return _u
}

// SetNillableSenderUsername sets the "sender_username" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSenderUsername(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSenderUsername(*v)
	}
	return _u
}

// ClearSenderUsername clears the value of the "sender_username" field.
func (_u *MessageUpdate) ClearSenderUsername() *MessageUpdate {
	_u.mutation.ClearSenderUsername()
	return _u
}

// SetText sets the "text" field.
func (_u *MessageUpdate) SetText(v string) *MessageUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableText(v *string) *MessageUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *MessageUpdate) SetSentAt(v time.Time) *MessageUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSentAt(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := message.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(message.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(message.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(message.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(message.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(message.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(message.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(message.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(message.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUsername(); ok {
		_spec.SetField(message.FieldSenderUsername, field.TypeString, value)
	}
	if _u.mutation.SenderUsernameCleared() {
		_spec.ClearField(message.FieldSenderUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(message.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(message.FieldSentAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *MessageUpdateOne) SetUpdateTime(v time.Time) *MessageUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MessageUpdateOne) SetMessageID(v int64) *MessageUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableMessageID(v *int64) *MessageUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *MessageUpdateOne) AddMessageID(v int64) *MessageUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *MessageUpdateOne) SetChatID(v int64) *MessageUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableChatID(v *int64) *MessageUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *MessageUpdateOne) AddChatID(v int64) *MessageUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *MessageUpdateOne) SetSenderID(v int64) *MessageUpdateOne {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSenderID(v *int64) *MessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *MessageUpdateOne) AddSenderID(v int64) *MessageUpdateOne {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *MessageUpdateOne) SetSenderName(v string) *MessageUpdateOne {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSenderName(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetSenderUsername sets the "sender_username" field.
func (_u *MessageUpdateOne) SetSenderUsername(v string) *MessageUpdateOne {
	_u.mutation.SetSenderUsername(v)
	return _u
}

// SetNillableSenderUsername sets the "sender_username" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSenderUsername(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSenderUsername(*v)
	}
	return _u
}

// ClearSenderUsername clears the value of the "sender_username" field.
func (_u *MessageUpdateOne) ClearSenderUsername() *MessageUpdateOne {
	_u.mutation.ClearSenderUsername()
	return _u
}

// SetText sets the "text" field.
func (_u *MessageUpdateOne) SetText(v string) *MessageUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableText(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *MessageUpdateOne) SetSentAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSentAt(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := message.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(message.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(message.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(message.FieldMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(message.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(message.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(message.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(message.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(message.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUsername(); ok {
		_spec.SetField(message.FieldSenderUsername, field.TypeString, value)
	}
	if _u.mutation.SenderUsernameCleared() {
		_spec.ClearField(message.FieldSenderUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(message.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(message.FieldSentAt, field.TypeTime, value)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
