// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/fachebot/talk-trace-bot/internal/ent/dailyrun"
	"github.com/fachebot/talk-trace-bot/internal/ent/message"
	"github.com/fachebot/talk-trace-bot/internal/ent/schema"
	"github.com/fachebot/talk-trace-bot/internal/ent/summary"
	"github.com/fachebot/talk-trace-bot/internal/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dailyrunMixin := schema.DailyRun{}.Mixin()
	dailyrunMixinFields0 := dailyrunMixin[0].Fields()
	_ = dailyrunMixinFields0
	dailyrunFields := schema.DailyRun{}.Fields()
	_ = dailyrunFields
	// dailyrunDescCreateTime is the schema descriptor for create_time field.
	dailyrunDescCreateTime := dailyrunMixinFields0[0].Descriptor()
	// dailyrun.DefaultCreateTime holds the default value on creation for the create_time field.
	dailyrun.DefaultCreateTime = dailyrunDescCreateTime.Default.(func() time.Time)
	// dailyrunDescUpdateTime is the schema descriptor for update_time field.
	dailyrunDescUpdateTime := dailyrunMixinFields0[1].Descriptor()
	// dailyrun.DefaultUpdateTime holds the default value on creation for the update_time field.
	dailyrun.DefaultUpdateTime = dailyrunDescUpdateTime.Default.(func() time.Time)
	// dailyrun.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	dailyrun.UpdateDefaultUpdateTime = dailyrunDescUpdateTime.UpdateDefault.(func() time.Time)
	messageMixin := schema.Message{}.Mixin()
	messageMixinFields0 := messageMixin[0].Fields()
	_ = messageMixinFields0
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreateTime is the schema descriptor for create_time field.
	messageDescCreateTime := messageMixinFields0[0].Descriptor()
	// message.DefaultCreateTime holds the default value on creation for the create_time field.
	message.DefaultCreateTime = messageDescCreateTime.Default.(func() time.Time)
	// messageDescUpdateTime is the schema descriptor for update_time field.
	messageDescUpdateTime := messageMixinFields0[1].Descriptor()
	// message.DefaultUpdateTime holds the default value on creation for the update_time field.
	message.DefaultUpdateTime = messageDescUpdateTime.Default.(func() time.Time)
	// message.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	message.UpdateDefaultUpdateTime = messageDescUpdateTime.UpdateDefault.(func() time.Time)
	summaryMixin := schema.Summary{}.Mixin()
	summaryMixinFields0 := summaryMixin[0].Fields()
	_ = summaryMixinFields0
	summaryFields := schema.Summary{}.Fields()
	_ = summaryFields
	// summaryDescCreateTime is the schema descriptor for create_time field.
	summaryDescCreateTime := summaryMixinFields0[0].Descriptor()
	// summary.DefaultCreateTime holds the default value on creation for the create_time field.
	summary.DefaultCreateTime = summaryDescCreateTime.Default.(func() time.Time)
	// summaryDescUpdateTime is the schema descriptor for update_time field.
	summaryDescUpdateTime := summaryMixinFields0[1].Descriptor()
	// summary.DefaultUpdateTime holds the default value on creation for the update_time field.
	summary.DefaultUpdateTime = summaryDescUpdateTime.Default.(func() time.Time)
	// summary.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	summary.UpdateDefaultUpdateTime = summaryDescUpdateTime.UpdateDefault.(func() time.Time)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreateTime is the schema descriptor for create_time field.
	taskDescCreateTime := taskMixinFields0[0].Descriptor()
	// task.DefaultCreateTime holds the default value on creation for the create_time field.
	task.DefaultCreateTime = taskDescCreateTime.Default.(func() time.Time)
	// taskDescUpdateTime is the schema descriptor for update_time field.
	taskDescUpdateTime := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdateTime holds the default value on creation for the update_time field.
	task.DefaultUpdateTime = taskDescUpdateTime.Default.(func() time.Time)
	// task.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	task.UpdateDefaultUpdateTime = taskDescUpdateTime.UpdateDefault.(func() time.Time)
}
