// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/talk-trace-bot/internal/ent/predicate"
	"github.com/fachebot/talk-trace-bot/internal/ent/summary"
)

// SummaryUpdate is the builder for updating Summary entities.
type SummaryUpdate struct {
	config
	hooks    []Hook
	mutation *SummaryMutation
}

// Where appends a list predicates to the SummaryUpdate builder.
func (_u *SummaryUpdate) Where(ps ...predicate.Summary) *SummaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SummaryUpdate) SetUpdateTime(v time.Time) *SummaryUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *SummaryUpdate) SetChatID(v int64) *SummaryUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableChatID(v *int64) *SummaryUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *SummaryUpdate) AddChatID(v int64) *SummaryUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *SummaryUpdate) SetSenderID(v int64) *SummaryUpdate {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableSenderID(v *int64) *SummaryUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *SummaryUpdate) AddSenderID(v int64) *SummaryUpdate {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *SummaryUpdate) SetSenderName(v string) *SummaryUpdate {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableSenderName(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetSenderUsername sets the "sender_username" field.
func (_u *SummaryUpdate) SetSenderUsername(v string) *SummaryUpdate {
	_u.mutation.SetSenderUsername(v)
	return _u
}

// SetNillableSenderUsername sets the "sender_username" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableSenderUsername(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetSenderUsername(*v)
	}
	return _u
}

// ClearSenderUsername clears the value of the "sender_username" field.
func (_u *SummaryUpdate) ClearSenderUsername() *SummaryUpdate {
	_u.mutation.ClearSenderUsername()
	return _u
}

// SetSenderNickname sets the "sender_nickname" field.
func (_u *SummaryUpdate) SetSenderNickname(v string) *SummaryUpdate {
	_u.mutation.SetSenderNickname(v)
	return _u
}

// SetNillableSenderNickname sets the "sender_nickname" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableSenderNickname(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetSenderNickname(*v)
	}
	return _u
}

// ClearSenderNickname clears the value of the "sender_nickname" field.
func (_u *SummaryUpdate) ClearSenderNickname() *SummaryUpdate {
	_u.mutation.ClearSenderNickname()
	return _u
}

// SetSummaryDate sets the "summary_date" field.
func (_u *SummaryUpdate) SetSummaryDate(v time.Time) *SummaryUpdate {
	_u.mutation.SetSummaryDate(v)
	return _u
}

// SetNillableSummaryDate sets the "summary_date" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableSummaryDate(v *time.Time) *SummaryUpdate {
	if v != nil {
		_u.SetSummaryDate(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SummaryUpdate) SetContent(v string) *SummaryUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SummaryUpdate) SetNillableContent(v *string) *SummaryUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// Mutation returns the SummaryMutation object of the builder.
func (_u *SummaryUpdate) Mutation() *SummaryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SummaryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SummaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SummaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SummaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SummaryUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := summary.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *SummaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(summary.Table, summary.Columns, sqlgraph.NewFieldSpec(summary.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(summary.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(summary.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(summary.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(summary.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(summary.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(summary.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUsername(); ok {
		_spec.SetField(summary.FieldSenderUsername, field.TypeString, value)
	}
	if _u.mutation.SenderUsernameCleared() {
		_spec.ClearField(summary.FieldSenderUsername, field.TypeString)
	}
	if value, ok := _u.mutation.SenderNickname(); ok {
		_spec.SetField(summary.FieldSenderNickname, field.TypeString, value)
	}
	if _u.mutation.SenderNicknameCleared() {
		_spec.ClearField(summary.FieldSenderNickname, field.TypeString)
	}
	if value, ok := _u.mutation.SummaryDate(); ok {
		_spec.SetField(summary.FieldSummaryDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(summary.FieldContent, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{summary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SummaryUpdateOne is the builder for updating a single Summary entity.
type SummaryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SummaryMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *SummaryUpdateOne) SetUpdateTime(v time.Time) *SummaryUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *SummaryUpdateOne) SetChatID(v int64) *SummaryUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableChatID(v *int64) *SummaryUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *SummaryUpdateOne) AddChatID(v int64) *SummaryUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *SummaryUpdateOne) SetSenderID(v int64) *SummaryUpdateOne {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableSenderID(v *int64) *SummaryUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *SummaryUpdateOne) AddSenderID(v int64) *SummaryUpdateOne {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *SummaryUpdateOne) SetSenderName(v string) *SummaryUpdateOne {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableSenderName(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetSenderUsername sets the "sender_username" field.
func (_u *SummaryUpdateOne) SetSenderUsername(v string) *SummaryUpdateOne {
	_u.mutation.SetSenderUsername(v)
	return _u
}

// SetNillableSenderUsername sets the "sender_username" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableSenderUsername(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetSenderUsername(*v)
	}
	return _u
}

// ClearSenderUsername clears the value of the "sender_username" field.
func (_u *SummaryUpdateOne) ClearSenderUsername() *SummaryUpdateOne {
	_u.mutation.ClearSenderUsername()
	return _u
}

// SetSenderNickname sets the "sender_nickname" field.
func (_u *SummaryUpdateOne) SetSenderNickname(v string) *SummaryUpdateOne {
	_u.mutation.SetSenderNickname(v)
	return _u
}

// SetNillableSenderNickname sets the "sender_nickname" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableSenderNickname(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetSenderNickname(*v)
	}
	return _u
}

// ClearSenderNickname clears the value of the "sender_nickname" field.
func (_u *SummaryUpdateOne) ClearSenderNickname() *SummaryUpdateOne {
	_u.mutation.ClearSenderNickname()
	return _u
}

// SetSummaryDate sets the "summary_date" field.
func (_u *SummaryUpdateOne) SetSummaryDate(v time.Time) *SummaryUpdateOne {
	_u.mutation.SetSummaryDate(v)
	return _u
}

// SetNillableSummaryDate sets the "summary_date" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableSummaryDate(v *time.Time) *SummaryUpdateOne {
	if v != nil {
		_u.SetSummaryDate(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SummaryUpdateOne) SetContent(v string) *SummaryUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SummaryUpdateOne) SetNillableContent(v *string) *SummaryUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// Mutation returns the SummaryMutation object of the builder.
func (_u *SummaryUpdateOne) Mutation() *SummaryMutation {
	return _u.mutation
}

// Where appends a list predicates to the SummaryUpdate builder.
func (_u *SummaryUpdateOne) Where(ps ...predicate.Summary) *SummaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SummaryUpdateOne) Select(field string, fields ...string) *SummaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Summary entity.
func (_u *SummaryUpdateOne) Save(ctx context.Context) (*Summary, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SummaryUpdateOne) SaveX(ctx context.Context) *Summary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SummaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SummaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SummaryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := summary.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *SummaryUpdateOne) sqlSave(ctx context.Context) (_node *Summary, err error) {
	_spec := sqlgraph.NewUpdateSpec(summary.Table, summary.Columns, sqlgraph.NewFieldSpec(summary.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Summary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, summary.FieldID)
		for _, f := range fields {
			if !summary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != summary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(summary.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(summary.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(summary.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(summary.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(summary.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(summary.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUsername(); ok {
		_spec.SetField(summary.FieldSenderUsername, field.TypeString, value)
	}
	if _u.mutation.SenderUsernameCleared() {
		_spec.ClearField(summary.FieldSenderUsername, field.TypeString)
	}
	if value, ok := _u.mutation.SenderNickname(); ok {
		_spec.SetField(summary.FieldSenderNickname, field.TypeString, value)
	}
	if _u.mutation.SenderNicknameCleared() {
		_spec.ClearField(summary.FieldSenderNickname, field.TypeString)
	}
	if value, ok := _u.mutation.SummaryDate(); ok {
		_spec.SetField(summary.FieldSummaryDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(summary.FieldContent, field.TypeString, value)
	}
	_node = &Summary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{summary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
