// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/talk-trace-bot/internal/ent/summary"
)

// SummaryCreate is the builder for creating a Summary entity.
type SummaryCreate struct {
	config
	mutation *SummaryMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *SummaryCreate) SetCreateTime(v time.Time) *SummaryCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableCreateTime(v *time.Time) *SummaryCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SummaryCreate) SetUpdateTime(v time.Time) *SummaryCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableUpdateTime(v *time.Time) *SummaryCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetChatID sets the "chat_id" field.
func (_c *SummaryCreate) SetChatID(v int64) *SummaryCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *SummaryCreate) SetSenderID(v int64) *SummaryCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetSenderName sets the "sender_name" field.
func (_c *SummaryCreate) SetSenderName(v string) *SummaryCreate {
	_c.mutation.SetSenderName(v)
	return _c
}

// SetSenderUsername sets the "sender_username" field.
func (_c *SummaryCreate) SetSenderUsername(v string) *SummaryCreate {
	_c.mutation.SetSenderUsername(v)
	return _c
}

// SetNillableSenderUsername sets the "sender_username" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableSenderUsername(v *string) *SummaryCreate {
	if v != nil {
		_c.SetSenderUsername(*v)
	}
	return _c
}

// SetSenderNickname sets the "sender_nickname" field.
func (_c *SummaryCreate) SetSenderNickname(v string) *SummaryCreate {
	_c.mutation.SetSenderNickname(v)
	return _c
}

// SetNillableSenderNickname sets the "sender_nickname" field if the given value is not nil.
func (_c *SummaryCreate) SetNillableSenderNickname(v *string) *SummaryCreate {
	if v != nil {
		_c.SetSenderNickname(*v)
	}
	return _c
}

// SetSummaryDate sets the "summary_date" field.
func (_c *SummaryCreate) SetSummaryDate(v time.Time) *SummaryCreate {
	_c.mutation.SetSummaryDate(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *SummaryCreate) SetContent(v string) *SummaryCreate {
	_c.mutation.SetContent(v)
	return _c
}

// Mutation returns the SummaryMutation object of the builder.
func (_c *SummaryCreate) Mutation() *SummaryMutation {
	return _c.mutation
}

// Save creates the Summary in the database.
func (_c *SummaryCreate) Save(ctx context.Context) (*Summary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SummaryCreate) SaveX(ctx context.Context) *Summary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SummaryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SummaryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SummaryCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := summary.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := summary.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SummaryCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Summary.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Summary.update_time"`)}
	}
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "Summary.chat_id"`)}
	}
	if _, ok := _c.mutation.SenderID(); !ok {
		return &ValidationError{Name: "sender_id", err: errors.New(`ent: missing required field "Summary.sender_id"`)}
	}
	if _, ok := _c.mutation.SenderName(); !ok {
		return &ValidationError{Name: "sender_name", err: errors.New(`ent: missing required field "Summary.sender_name"`)}
	}
	if _, ok := _c.mutation.SummaryDate(); !ok {
		return &ValidationError{Name: "summary_date", err: errors.New(`ent: missing required field "Summary.summary_date"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Summary.content"`)}
	}
	return nil
}

func (_c *SummaryCreate) sqlSave(ctx context.Context) (*Summary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SummaryCreate) createSpec() (*Summary, *sqlgraph.CreateSpec) {
	var (
		_node = &Summary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(summary.Table, sqlgraph.NewFieldSpec(summary.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(summary.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(summary.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(summary.FieldChatID, field.TypeInt64, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.SenderID(); ok {
		_spec.SetField(summary.FieldSenderID, field.TypeInt64, value)
		_node.SenderID = value
	}
	if value, ok := _c.mutation.SenderName(); ok {
		_spec.SetField(summary.FieldSenderName, field.TypeString, value)
		_node.SenderName = value
	}
	if value, ok := _c.mutation.SenderUsername(); ok {
		_spec.SetField(summary.FieldSenderUsername, field.TypeString, value)
		_node.SenderUsername = value
	}
	if value, ok := _c.mutation.SenderNickname(); ok {
		_spec.SetField(summary.FieldSenderNickname, field.TypeString, value)
		_node.SenderNickname = value
	}
	if value, ok := _c.mutation.SummaryDate(); ok {
		_spec.SetField(summary.FieldSummaryDate, field.TypeTime, value)
		_node.SummaryDate = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(summary.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	return _node, _spec
}

// SummaryCreateBulk is the builder for creating many Summary entities in bulk.
type SummaryCreateBulk struct {
	config
	err      error
	builders []*SummaryCreate
}

// Save creates the Summary entities in the database.
func (_c *SummaryCreateBulk) Save(ctx context.Context) ([]*Summary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Summary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SummaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SummaryCreateBulk) SaveX(ctx context.Context) []*Summary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SummaryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SummaryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
