// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/talk-trace-bot/internal/ent/summary"
)

// Summary is the model entity for the Summary schema.
type Summary struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// 群聊ID
	ChatID int64 `json:"chat_id,omitempty"`
	// 发送者用户ID
	SenderID int64 `json:"sender_id,omitempty"`
	// 发送者名称
	SenderName string `json:"sender_name,omitempty"`
	// 发送者用户名
	SenderUsername string `json:"sender_username,omitempty"`
	// 发送者昵称
	SenderNickname string `json:"sender_nickname,omitempty"`
	// 摘要日期
	SummaryDate time.Time `json:"summary_date,omitempty"`
	// 摘要内容
	Content      string `json:"content,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Summary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case summary.FieldID, summary.FieldChatID, summary.FieldSenderID:
			values[i] = new(sql.NullInt64)
		case summary.FieldSenderName, summary.FieldSenderUsername, summary.FieldSenderNickname, summary.FieldContent:
			values[i] = new(sql.NullString)
		case summary.FieldCreateTime, summary.FieldUpdateTime, summary.FieldSummaryDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Summary fields.
func (_m *Summary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case summary.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case summary.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case summary.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case summary.FieldChatID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chat_id", values[i])
			} else if value.Valid {
				_m.ChatID = value.Int64
			}
		case summary.FieldSenderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = value.Int64
			}
		case summary.FieldSenderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_name", values[i])
			} else if value.Valid {
				_m.SenderName = value.String
			}
		case summary.FieldSenderUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_username", values[i])
			} else if value.Valid {
				_m.SenderUsername = value.String
			}
		case summary.FieldSenderNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_nickname", values[i])
			} else if value.Valid {
				_m.SenderNickname = value.String
			}
		case summary.FieldSummaryDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field summary_date", values[i])
			} else if value.Valid {
				_m.SummaryDate = value.Time
			}
		case summary.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Summary.
// This includes values selected through modifiers, order, etc.
func (_m *Summary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Summary.
// Note that you need to call Summary.Unwrap() before calling this method if this Summary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Summary) Update() *SummaryUpdateOne {
	return NewSummaryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Summary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Summary) Unwrap() *Summary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Summary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Summary) String() string {
	var builder strings.Builder
	builder.WriteString("Summary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("chat_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChatID))
	builder.WriteString(", ")
	builder.WriteString("sender_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SenderID))
	builder.WriteString(", ")
	builder.WriteString("sender_name=")
	builder.WriteString(_m.SenderName)
	builder.WriteString(", ")
	builder.WriteString("sender_username=")
	builder.WriteString(_m.SenderUsername)
	builder.WriteString(", ")
	builder.WriteString("sender_nickname=")
	builder.WriteString(_m.SenderNickname)
	builder.WriteString(", ")
	builder.WriteString("summary_date=")
	builder.WriteString(_m.SummaryDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteByte(')')
	return builder.String()
}

// Summaries is a parsable slice of Summary.
type Summaries []*Summary
