// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/talk-trace-bot/internal/ent/predicate"
	"github.com/fachebot/talk-trace-bot/internal/ent/task"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TaskUpdate) SetUpdateTime(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *TaskUpdate) SetChatID(v int64) *TaskUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableChatID(v *int64) *TaskUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *TaskUpdate) AddChatID(v int64) *TaskUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *TaskUpdate) SetStartTime(v time.Time) *TaskUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStartTime(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *TaskUpdate) SetEndTime(v time.Time) *TaskUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableEndTime(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v task.Status) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *task.Status) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TaskUpdate) SetCompletedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCompletedAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TaskUpdate) ClearCompletedAt() *TaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TaskUpdate) SetErrorMessage(v string) *TaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableErrorMessage(v *string) *TaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TaskUpdate) ClearErrorMessage() *TaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSummaryContent sets the "summary_content" field.
func (_u *TaskUpdate) SetSummaryContent(v string) *TaskUpdate {
	_u.mutation.SetSummaryContent(v)
	return _u
}

// SetNillableSummaryContent sets the "summary_content" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSummaryContent(v *string) *TaskUpdate {
	if v != nil {
		_u.SetSummaryContent(*v)
	}
	return _u
}

// ClearSummaryContent clears the value of the "summary_content" field.
func (_u *TaskUpdate) ClearSummaryContent() *TaskUpdate {
	_u.mutation.ClearSummaryContent()
	return _u
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := task.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(task.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(task.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(task.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(task.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(task.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(task.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(task.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(task.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(task.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SummaryContent(); ok {
		_spec.SetField(task.FieldSummaryContent, field.TypeString, value)
	}
	if _u.mutation.SummaryContentCleared() {
		_spec.ClearField(task.FieldSummaryContent, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *TaskUpdateOne) SetUpdateTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *TaskUpdateOne) SetChatID(v int64) *TaskUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableChatID(v *int64) *TaskUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *TaskUpdateOne) AddChatID(v int64) *TaskUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *TaskUpdateOne) SetStartTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStartTime(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *TaskUpdateOne) SetEndTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableEndTime(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v task.Status) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *task.Status) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TaskUpdateOne) SetCompletedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCompletedAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TaskUpdateOne) ClearCompletedAt() *TaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *TaskUpdateOne) SetErrorMessage(v string) *TaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableErrorMessage(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *TaskUpdateOne) ClearErrorMessage() *TaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSummaryContent sets the "summary_content" field.
func (_u *TaskUpdateOne) SetSummaryContent(v string) *TaskUpdateOne {
	_u.mutation.SetSummaryContent(v)
	return _u
}

// SetNillableSummaryContent sets the "summary_content" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSummaryContent(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetSummaryContent(*v)
	}
	return _u
}

// ClearSummaryContent clears the value of the "summary_content" field.
func (_u *TaskUpdateOne) ClearSummaryContent() *TaskUpdateOne {
	_u.mutation.ClearSummaryContent()
	return _u
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := task.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(task.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(task.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(task.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(task.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(task.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(task.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(task.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(task.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(task.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SummaryContent(); ok {
		_spec.SetField(task.FieldSummaryContent, field.TypeString, value)
	}
	if _u.mutation.SummaryContentCleared() {
		_spec.ClearField(task.FieldSummaryContent, field.TypeString)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
