// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DailyRun is the predicate function for dailyrun builders.
type DailyRun func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Summary is the predicate function for summary builders.
type Summary func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
