// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/talk-trace-bot/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldUpdateTime, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldMessageID, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldChatID, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderID, v))
}

// SenderName applies equality check predicate on the "sender_name" field. It's identical to SenderNameEQ.
func SenderName(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderName, v))
}

// SenderUsername applies equality check predicate on the "sender_username" field. It's identical to SenderUsernameEQ.
func SenderUsername(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderUsername, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldText, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSentAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldUpdateTime, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldMessageID, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldChatID, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderID, v))
}

// SenderNameEQ applies the EQ predicate on the "sender_name" field.
func SenderNameEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderName, v))
}

// SenderNameNEQ applies the NEQ predicate on the "sender_name" field.
func SenderNameNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderName, v))
}

// SenderNameIn applies the In predicate on the "sender_name" field.
func SenderNameIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderName, vs...))
}

// SenderNameNotIn applies the NotIn predicate on the "sender_name" field.
func SenderNameNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderName, vs...))
}

// SenderNameGT applies the GT predicate on the "sender_name" field.
func SenderNameGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderName, v))
}

// SenderNameGTE applies the GTE predicate on the "sender_name" field.
func SenderNameGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderName, v))
}

// SenderNameLT applies the LT predicate on the "sender_name" field.
func SenderNameLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderName, v))
}

// SenderNameLTE applies the LTE predicate on the "sender_name" field.
func SenderNameLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderName, v))
}

// SenderNameContains applies the Contains predicate on the "sender_name" field.
func SenderNameContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderName, v))
}

// SenderNameHasPrefix applies the HasPrefix predicate on the "sender_name" field.
func SenderNameHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderName, v))
}

// SenderNameHasSuffix applies the HasSuffix predicate on the "sender_name" field.
func SenderNameHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderName, v))
}

// SenderNameEqualFold applies the EqualFold predicate on the "sender_name" field.
func SenderNameEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderName, v))
}

// SenderNameContainsFold applies the ContainsFold predicate on the "sender_name" field.
func SenderNameContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderName, v))
}

// SenderUsernameEQ applies the EQ predicate on the "sender_username" field.
func SenderUsernameEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderUsername, v))
}

// SenderUsernameNEQ applies the NEQ predicate on the "sender_username" field.
func SenderUsernameNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderUsername, v))
}

// SenderUsernameIn applies the In predicate on the "sender_username" field.
func SenderUsernameIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderUsername, vs...))
}

// SenderUsernameNotIn applies the NotIn predicate on the "sender_username" field.
func SenderUsernameNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderUsername, vs...))
}

// SenderUsernameGT applies the GT predicate on the "sender_username" field.
func SenderUsernameGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderUsername, v))
}

// SenderUsernameGTE applies the GTE predicate on the "sender_username" field.
func SenderUsernameGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderUsername, v))
}

// SenderUsernameLT applies the LT predicate on the "sender_username" field.
func SenderUsernameLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderUsername, v))
}

// SenderUsernameLTE applies the LTE predicate on the "sender_username" field.
func SenderUsernameLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderUsername, v))
}

// SenderUsernameContains applies the Contains predicate on the "sender_username" field.
func SenderUsernameContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderUsername, v))
}

// SenderUsernameHasPrefix applies the HasPrefix predicate on the "sender_username" field.
func SenderUsernameHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderUsername, v))
}

// SenderUsernameHasSuffix applies the HasSuffix predicate on the "sender_username" field.
func SenderUsernameHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderUsername, v))
}

// SenderUsernameIsNil applies the IsNil predicate on the "sender_username" field.
func SenderUsernameIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldSenderUsername))
}

// SenderUsernameNotNil applies the NotNil predicate on the "sender_username" field.
func SenderUsernameNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldSenderUsername))
}

// SenderUsernameEqualFold applies the EqualFold predicate on the "sender_username" field.
func SenderUsernameEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderUsername, v))
}

// SenderUsernameContainsFold applies the ContainsFold predicate on the "sender_username" field.
func SenderUsernameContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderUsername, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldText, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSentAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
